In [2]:
import pandas as pd
import numpy as np

In [5]:
dv=pd.read_csv(r"D:\Prc Data\Practice Question\customers_dataset.csv")
df=pd.read_csv(r"D:\Prc Data\Practice Question\ecommerce_orders_dataset.csv")

In [6]:
df.head(10)  # 1 Show the first 10 rows of the orders dataset.

,order_id,order_date,customer_id,city,product_category,product_name,quantity,price,discount_percent,payment_method,rating,returned
0,1,2023-03-13,189,Kolkata,Electronics,Laptop,4,1160,10,Debit Card,5.0,0
1,2,2023-03-29,100,Delhi,Clothing,Jeans,3,37494,10,UPI,3.0,0
2,3,2023-10-04,161,Hyderabad,Electronics,Smartwatch,2,2733,15,UPI,4.0,0
3,4,2024-04-19,59,Delhi,Electronics,Laptop,5,27780,0,Credit Card,2.0,0
4,5,2024-07-20,244,Delhi,Electronics,Smartwatch,4,489,10,Cash on Delivery,1.0,0
5,6,2023-06-16,274,Chennai,Clothing,Dress,3,41906,20,Debit Card,4.0,1
6,7,2023-12-12,53,Kolkata,Electronics,Smartphone,2,43301,0,Cash on Delivery,2.0,0
7,8,2023-02-04,206,Delhi,Home,Lamp,4,48855,20,Credit Card,1.0,0
8,9,2024-04-21,191,Bangalore,Home,Mixer,4,19757,5,Cash on Delivery,2.0,0
9,10,2023-09-27,271,Pune,Electronics,Headphones,2,37365,15,Debit Card,NaN,0

In [7]:
df.shape      #2 Check the shape of the orders dataset.

(1200, 12)

In [9]:
df.columns #3 Display all column names in the orders dataset.

Index(['order_id', 'order_date', 'customer_id', 'city', 'product_category',
       'product_name', 'quantity', 'price', 'discount_percent',
       'payment_method', 'rating', 'returned'],
      dtype='object')

In [11]:
df.dtypes   #4 Check the data types of all columns.

order_id              int64
order_date           object
customer_id           int64
city                 object
product_category     object
product_name         object
quantity              int64
price                 int64
discount_percent      int64
payment_method       object
rating              float64
returned              int64
dtype: object

In [12]:
df.isnull().sum() #5 Find how many missing values exist in each column.

order_id              0
order_date            0
customer_id           0
city                  0
product_category      0
product_name          0
quantity              0
price                 0
discount_percent      0
payment_method        0
rating              197
returned              0
dtype: int64

In [16]:
df[['order_id','product_name','price','quantity']]  #6 Show only these columns: order_id, product_name, price, quantity.

      order_id product_name  price  quantity
0            1       Laptop   1160         4
1            2        Jeans  37494         3
2            3   Smartwatch   2733         2
3            4       Laptop  27780         5
4            5   Smartwatch    489         4
...        ...          ...    ...       ...
1195      1196        Dress  26505         1
1196      1197   Smartphone  45832         4
1197      1198       Laptop  37366         4
1198      1199        Mixer  39665         4
1199      1200   Gym Gloves  41393         5

[1200 rows x 4 columns]

In [20]:
df[df['price']>10000 ]#7 Filter all orders where price is greater than 10,000.

,order_id,order_date,customer_id,city,product_category,product_name,quantity,price,discount_percent,payment_method,rating,returned
1,2,2023-03-29,100,Delhi,Clothing,Jeans,3,37494,10,UPI,3.0,0
3,4,2024-04-19,59,Delhi,Electronics,Laptop,5,27780,0,Credit Card,2.0,0
5,6,2023-06-16,274,Chennai,Clothing,Dress,3,41906,20,Debit Card,4.0,1
6,7,2023-12-12,53,Kolkata,Electronics,Smartphone,2,43301,0,Cash on Delivery,2.0,0
7,8,2023-02-04,206,Delhi,Home,Lamp,4,48855,20,Credit Card,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1196,2024-07-13,191,Kolkata,Clothing,Dress,1,26505,10,UPI,NaN,0
1196,1197,2024-02-05,296,Hyderabad,Electronics,Smartphone,4,45832,10,Cash on Delivery,1.0,0
1197,1198,2024-09-24,226,Mumbai,Electronics,Laptop,4,37366,0,Credit Card,2.0,0
1198,1199,2023-08-04,43,Chennai,Home,Mixer,4,39665,15,UPI,3.0,0
1199,1200,2024-01-25,22,Chennai,Sports,Gym Gloves,5,41393,0,Debit Card,1.0,0

In [24]:
df[df['city']=='banglore'] #8 Filter orders where city = Bangalore.

Empty DataFrame
Columns: [order_id, order_date, customer_id, city, product_category, product_name, quantity, price, discount_percent, payment_method, rating, returned]
Index: []

In [29]:
(df['price']>20000 )& (df['quantity']>= 2 ) # 9 Filter orders where price > 20000 AND quantity >= 2.

0       False
1        True
2       False
3        True
4       False
        ...
1195    False
1196     True
1197     True
1198     True
1199     True
Length: 1200, dtype: bool

In [34]:
df.sort_values(by='price', ascending =False )  #10 Sort the dataset by price (highest first).

,order_id,order_date,customer_id,city,product_category,product_name,quantity,price,discount_percent,payment_method,rating,returned
911,912,2024-06-30,119,Mumbai,Clothing,Dress,2,49923,20,UPI,NaN,0
901,902,2023-10-13,49,Pune,Electronics,Headphones,2,49849,15,Cash on Delivery,4.0,1
1016,1017,2024-01-24,218,Hyderabad,Home,Lamp,1,49838,5,Debit Card,5.0,0
989,990,2023-10-04,24,Mumbai,Sports,Football,3,49776,5,Cash on Delivery,NaN,1
900,901,2024-07-28,68,Bangalore,Clothing,Jacket,2,49752,15,Cash on Delivery,5.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1094,1095,2023-01-16,205,Chennai,Sports,Tennis Racket,2,511,15,Debit Card,5.0,0
16,17,2024-07-07,179,Mumbai,Clothing,Jacket,3,506,5,Credit Card,1.0,0
4,5,2024-07-20,244,Delhi,Electronics,Smartwatch,4,489,10,Cash on Delivery,1.0,0
581,582,2023-04-19,35,Hyderabad,Electronics,Headphones,5,436,10,Cash on Delivery,NaN,0
375,376,2024-09-28,167,Kolkata,Electronics,Smartphone,2,397,10,Cash on Delivery,NaN,0

In [37]:
df.groupby('city')['order_id'].count() #11 Find total number of orders per city.

city
Bangalore    154
Chennai      184
Delhi        169
Hyderabad    169
Kolkata      170
Mumbai       172
Pune         182
Name: order_id, dtype: int64

In [41]:
df['product_category'].nunique()  #12 Find number of unique product categories.

4

In [44]:
df['price'].mean() #13 Find average price of products.

np.float64(24969.635833333334)

In [46]:
df['total_price']=df['price']*df['quantity'] #14 Create a new column total_price = price * quantity.

In [47]:
df['price'].max()  #15 Find the maximum product price in the dataset.

np.int64(49923)

In [49]:
df['price'].min()   #16 Find the minimum product price.

np.int64(397)

In [55]:
df[df['rating'].isnull()]    #  17 Show all orders where rating is missing.

,order_id,order_date,customer_id,city,product_category,product_name,quantity,price,discount_percent,payment_method,rating,returned,total_price
9,10,2023-09-27,271,Pune,Electronics,Headphones,2,37365,15,Debit Card,NaN,0,74730
20,21,2024-10-01,231,Pune,Electronics,Smartphone,4,26239,10,UPI,NaN,0,104956
23,24,2024-11-22,113,Hyderabad,Clothing,Dress,3,28321,0,Cash on Delivery,NaN,1,84963
25,26,2024-10-03,220,Hyderabad,Home,Table,1,27036,5,Cash on Delivery,NaN,0,27036
27,28,2024-02-05,255,Pune,Electronics,Laptop,4,33270,10,UPI,NaN,0,133080
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1174,1175,2023-12-23,145,Chennai,Sports,Yoga Mat,1,17370,5,UPI,NaN,0,17370
1175,1176,2023-06-30,83,Hyderabad,Electronics,Laptop,3,21102,5,Credit Card,NaN,0,63306
1178,1179,2023-07-28,93,Pune,Clothing,Dress,1,30898,5,Cash on Delivery,NaN,0,30898
1184,1185,2023-10-24,203,Hyderabad,Clothing,Jacket,5,6672,5,Debit Card,NaN,0,33360
1195,1196,2024-07-13,191,Kolkata,Clothing,Dress,1,26505,10,UPI,NaN,0,26505

In [60]:
df['rating'].fillna(0, inplace=True)  #18 Replace missing ratings with 0.

In [69]:
# 19 Count how many orders were returned.
df[df['returned'] == 1].shape[0]

106